# Generated by Django 5.0.6 on 2024-05-31 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('condado', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('taxes', models.FloatField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('modo_declaracion', models.CharField(max_length=100)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento_conyuge', models.DateField(blank=True, null=True)),
                ('estatus_conyuge', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacion_conyuge', models.CharField(blank=True, max_length=100, null=True)),
                ('cuanto_declara_conyuge', models.FloatField(blank=True, null=True)),
                ('aplica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estatus', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('cuanto_declara', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('compania', models.CharField(max_length=100)),
                ('link_plan', models.URLField()),
                ('credito_fiscal', models.FloatField()),
                ('primas_mensual', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.vendedor')),
            ],
        ),
    ]
