# Generated by Django 5.0.6 on 2024-06-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cliente_options_alter_dependiente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [('view_all_sales', 'Can view all sales')], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='clientes/audios/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/images/'),
        ),
        migrations.AddField(
            model_name='dependiente',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='dependientes/audios/'),
        ),
        migrations.AddField(
            model_name='dependiente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dependientes/images/'),
        ),
        migrations.AddField(
            model_name='venta',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ventas/audios/'),
        ),
        migrations.AddField(
            model_name='venta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/images/'),
        ),
    ]
