# Generated by Django 5.0.6 on 2024-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_options_cliente_audio_cliente_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dependiente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
