# Generated by Django 5.0.6 on 2024-06-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cliente_observaciones_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('can_view_clientes', 'Can view all clientes'), ('can_export_clientes', 'Can export clientes data'), ('can_edit_clientes', 'Can edit clientes')], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='dependiente',
            options={'permissions': [('can_view_dependientes', 'Can view all dependientes'), ('can_edit_dependientes', 'Can edit dependientes')], 'verbose_name': 'dependiente', 'verbose_name_plural': 'dependientes'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'permissions': [('can_view_vendedores', 'Can view all vendedores'), ('can_edit_vendedores', 'Can edit vendedores')], 'verbose_name': 'vendedor', 'verbose_name_plural': 'vendedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [('view_all_sales', 'Can view all sales'), ('can_export_sales', 'Can export sales data'), ('can_edit_sales', 'Can edit sales')], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
    ]
